### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by kjarex** [brndd/vanilla-tweaks#14]
Is there any chance to support the mac client as well?
How did you figure out the offsets (so one could try to do the same for the mac version)?

Thanks

**Comment by brndd** [comment]
Supporting the native Mac client is highly unlikely, as I don't own any computer that can run it. Is running the Windows client using Wine not an option?

> How did you figure out the offsets (so one could try to do the same for the mac version)?

I used [Ghidra](https://ghidra-sre.org/) and a couple of debuggers, primarily gdb. Cheat Engine can also be helpful.

For finding the offsets on the Mac client, the first thing I would recommend trying is opening the Windows client in Ghidra, looking up the offsets for the different patches from this tool, and then performing a search for some of the bytes surrounding that offset in the Mac client to try and find the same code in there. Unfortunately the chances of this working are slim, as the Mac client is compiled using a different compiler... but it's worth a try, because it's a lot less effort than the alternative.

If (when) that fails, you basically have to start reversing the Mac client from scratch, which is a big task. Many of the offsets used in this tool were found with the help of pre-existing reverse engineering knowledge from communities like Ownedcore, and there's a lot less of that knowledge available for the Mac client.
