### ISSUE TITLE
Disable 'Sound in Background' not working

### ISSUE THREAD

**Issue by psoaln** [brndd/vanilla-tweaks#20]
The command:
./vanilla-tweaks --no-sound-in-background --nameplatedistance 60 WoW.exe
does not disable the sound of WoW when in the background. It appears to skip the patch altogether.

![j6fogty](https://github.com/brndd/vanilla-tweaks/assets/116851112/e478f86b-37d2-4aef-a7a0-02db6684bcf6)

**Comment by brndd** [comment]
That's by design. The flags simply disable the patches, they don't apply the opposite patch on the executable.

I'm guessing the executable you're patching already has the sound in background patch applied to it? You'll have to either replace it with an unmodified executable, or reverse the patch manually. If it's the exact same patch this patcher applies, then changing the byte at 0x3A4869 from 0x27 to 0x14 using a hex editor should undo it.
