### ISSUE TITLE
request to share your work

### ISSUE THREAD

**Issue by WuVenus** [brndd/vanilla-tweaks#29]
![21312312](https://github.com/brndd/vanilla-tweaks/assets/144596429/0e5be523-24a1-4171-92f8-8908c1003f1a)

**Comment by WuVenus** [comment]
very want to get Blizzard default nameplates overlap!!!!

Request to share
Thank you very much!

**Comment by brndd** [comment]
It was just a quick and dirty hack into the ShaguTweaks addon. It didn't work (the nameplates were completely broken; text and healthbars in the wrong place etc.), so I scrapped the idea and don't have any of the code anymore.

**Comment by WuVenus** [comment]
If overlapping is required alone without text health can be successful?

**Comment by WuVenus** [comment]
> It was just a quick and dirty hack into the ShaguTweaks addon. It didn't work (the nameplates were completely broken; text and healthbars in the wrong place etc.), so I scrapped the idea and don't have any of the code anymore.

If overlapping is required alone without text health can be successful?

**Comment by brndd** [comment]
It was the name and level text that was messed up. If I remember correctly, they were both positioned in the top left corner and overlapping with one another.

This is probably because of the way they're anchored within the plate's container. It might be possible to make things work by tweaking the nameplate UI element's properties to match the way ShaguPlates are laid out, but I did not experiment with this.
